export const JobStatus = {
  NEW_WAITING: "NEW_WAITING",
  NEW_CHOOSING: "NEW_CHOOSING",
  MATCHED: "MATCHED",
  AGREED: "AGREED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
